export const CallType = {
  CHAT_PERSONAL_CODE: "CHAT_PERSONAL_CODE",
  CHAT_STRANGER: "CHAT_STRANGER",
  VIDEO_PERSONAL_CODE: "VIDEO_PERSONAL_CODE",
  VIDEO_STRANGER: "VIDEO_STRANGER",
};

export const PreOfferAnswer = {
  CALLEE_NOT_FOUND: "CALLEE_NOT_FOUND",
  CALL_ACCEPTED: "CALL_ACCEPTED",
  CALL_REJECTED: "CALL_REJECTED",
  CALL_UNAVAILABLE: "CALL_UNAVAILABLE",
};

export const WebRTCSignaling = {
  OFFER: "OFFER",
  ANSWER: "ANSWER",
  ICE_CANDIDATE: "ICE_CANDIDATE",
};

export const CallState = {
  AVAILABLE: "AVAILABLE",
  UNAVAILABLE: "UNAVAILABLE",
  AVAILABLE_CHAT_ONLY: "AVAILABLE_CHAT_ONLY",
};

export const ICE_SERVERS = [{ urls: "stun:stun.l.google.com:19302" }];
